version: '3'

services:
    postgres:
        image: postgres:latest
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=superuser
            - POSTGRES_USER=superuser
            - POSTGRES_DB=leapchat
        volumes:
            - ./_docker-volumes/postgres:/var/lib/postgresql/data
    postgrest:
        image: suzel/docker-postgrest:latest
        ports:
            - "3214:3000"
        environment:
            PGRST_DB_URI: "postgres://superuser:superuser@postgres:5432/leapchat"
        depends_on:
            - postgres
    adminer:
        image: adminer
        ports:
            - 8081:8081